/* Generated by Cython 0.23.5 */

#ifndef __PYX_HAVE__plot
#define __PYX_HAVE__plot


#ifndef __PYX_HAVE_API__plot

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) plot(std::vector<float>  const &, std::vector<float>  const &, float, float, float, float, std::string const &);
__PYX_EXTERN_C DL_IMPORT(void) save_plot(std::string const &, std::string const &, std::string const &);

#endif /* !__PYX_HAVE_API__plot */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initplot(void);
#else
PyMODINIT_FUNC PyInit_plot(void);
#endif

#endif /* !__PYX_HAVE__plot */
